### ISSUE TITLE
点击 某个tab 时，判断下用户登录状态

### ISSUE THREAD

**Issue by Carlxx** [forvv231/EasyNavigition#1]
点击 某个tab 时，判断下用户登录状态，拦截被点击 tab 的状态，这个功能 后期 后添加么

**Comment by forvv231** [comment]
改了好多东西、有点慢了、
Tab点击事件return true就可以拦截页面切换

**Comment by Carlxx** [comment]
大佬，非常感谢，回手就是一个赞！

**Comment by VVVVictorJ** [comment]
aspectj 切面注入
